# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.cache/wt [current_project]
set_property parent.project_path D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_mem {
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/imports/save/test.mem
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/imports/save/pointer.mem
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/imports/save/background.mem
}
read_verilog -library xil_defaultlib {
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/cell_unit.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/vga.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/ram.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/ps2_tx.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/ps2_rx.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/frame_buffer.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/automaton.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/logic_processor.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/ps2_mouse.v
  D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files D:/4x10msv/LearingFiles/DigitCircuit/project/CelluarAutomata_FPGA/CelluarAutomata_FPGA.srcs/constrs_1/new/top.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
